version: "3.8"
services:
    service:
        build:
            context: ./application
        image: article-api
        env_file:
            - api.env
        networks:
            backend:
        ports:
            - "5000:5000"
        depends_on:
            - db
        links:
            - "db"
    db:
        image: postgres:latest
        restart: always
        env_file:
            - .env
        ports:
            - "3333:5432"
        volumes:
            - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
            - ./db-data/:/var/lib/postgresql/data/
        networks:
            backend:
    test-service:
        depends_on:
            - service
        build:
            context: ./tests
        image: article-api-test
        command: python -m pytest

networks:
    backend:
